spring:
  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/peerflow
    username: juhyelee
    password: 'juhyelee'
#    username: ${POSTGRES_USER}
#    password: ${POSTGRES_PASSWORD}
